//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vestforsyningen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opgaver
    {
        public int id { get; set; }
        public string addresse { get; set; }
        public Nullable<System.DateTime> dato { get; set; }
        public string beskrivelse { get; set; }
        public string udføres { get; set; }
        public string jobnr { get; set; }
        public Nullable<int> fk_stauts { get; set; }
        public Nullable<int> fk_kategori { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual status status { get; set; }
    }
}
